name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Show available destinations
      run: |
        cd iOS
        xcodebuild -project PasswordGeneratorApp.xcodeproj -scheme PasswordGeneratorApp -showdestinations

    - name: Build for iOS Simulator
      run: |
        cd iOS
        xcodebuild clean build \
          -project PasswordGeneratorApp.xcodeproj \
          -scheme PasswordGeneratorApp \
          -destination "platform=iOS Simulator,name=iPhone 16" \
          -configuration Debug

    - name: Archive for Device (Development)
      run: |
        cd iOS
        xcodebuild clean archive \
          -project PasswordGeneratorApp.xcodeproj \
          -scheme PasswordGeneratorApp \
          -destination "generic/platform=iOS" \
          -configuration Release \
          -archivePath ../build/PasswordGeneratorApp.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      continue-on-error: true

    - name: Create IPA (if archive succeeded)
      run: |
        cd iOS
        if [ -d "../build/PasswordGeneratorApp.xcarchive" ]; then
          xcodebuild -exportArchive \
            -archivePath ../build/PasswordGeneratorApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath ../build/export
        else
          echo "Archive step failed, skipping IPA creation"
        fi
      continue-on-error: true

    - name: Upload iOS Simulator Build
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Simulator-App
        path: |
          /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphonesimulator/PasswordGeneratorApp.app
        retention-days: 30

    - name: Upload iOS Archive (if exists)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: iOS-Archive
        path: |
          build/
        retention-days: 30

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/export/*.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
